logging:
  level:
    # Основные пакеты Spring Cloud Gateway
    org.springframework.cloud.gateway: DEBUG
    org.springframework.web.reactive: DEBUG

    # Netty (если нужно логировать низкоуровневые HTTP-запросы/ответы)
    reactor.netty.http.client: DEBUG
    reactor.netty.http.server: DEBUG

server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always


spring:
  cloud:
    gateway:
      discovery.locator.enabled: true
      routes:
        - id: category-service_route
          uri: lb://category-service
          predicates:
            - Path=/admin/categories/**, /categories/**


        - id: event-service_route
          uri: lb://event-service
          predicates:
            - Path=/users/{userId}/events/**, /admin/events/**, /events/**


        - id: compilation-service_route
          uri: lb://compilation-service
          predicates:
            - Path=/compilations/**, /admin/compilations/**



        - id: user-service_route
          uri: lb://user-service
          predicates:
            - Path=/admin/users/**



        - id: request-service_route
          uri: lb://request-service
          predicates:
            - Path=/users/{userId}/requests/**


        - id: comment-service_route
          uri: lb://comment-service
          predicates:
            - Path=/admin/events/{eventId}/comments/**, /admin/comments/**, /users/{userId}/events/{eventId}/comments/**, /events/{eventId}/comments/**

