logging:
  level:
    ru.practicum.event: TRACE
    org:
      springframework:
        orm:
          jpa: INFO
          jpa.JpaTransactionManager: INFO
        transaction: INFO
        transaction.interceptor: INFO
      springframework.cloud.netflix.eureka: INFO
      springframework.web.client.RestTemplate: WARN
      org.springframework.cloud.openfeign: DEBUG
      com.fasterxml.jackson: DEBUG
      apache.kafka: INFO
    feign.Logger: WARN
server:
  port: 0
#  port: 12345

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/ewm_event
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: password

  sql:
    init:
      mode: always
  jpa:
#    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
#        format_sql: true
#        time_zone: UTC
#        default_schema: public

  cloud:
    openfeign:
      client:
        config:
          default:
#           connectTimeout: 5000
#           readTimeout: 5000
            loggerLevel: BASIC
      #  NONE Ничего (по умолчанию)
      #  BASIC Только метод, URL, код ответа, время
      #  HEADERS BASIC + заголовки запроса и ответа
      #  FULL HEADERS + тело запроса и ответа
      circuitbreaker:
        enabled: true
        alphanumeric-ids:
          enabled: true

resilience4j:
  circuitbreaker:
  configs:
    default:
      slidingWindowSize: 10
      failureRateThreshold: 50
  instances:
    event-service:
      slidingWindowSize: 10
      waitDurationInOpenState: 10000 # 10 секунд в миллисекундах
      permittedNumberOfCallsInHalfOpenState: 5
      slidingWindowType: COUNT_BASED
      minimumNumberOfCalls: 10
      automaticTransitionFromOpenToHalfOpenEnabled: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

discovery:
  services:
    stats-server-id:  stats-server

grpc:
  client:
    analyzer: # <- должно соответствовать значению в @GrpcClient
      address: 'discovery:///analyzer' # адрес gRPC-сервиса
      enableKeepAlive: true
      keepAliveWithoutCalls: true
      negotiation-type: plaintext
    collector: # <- должно соответствовать значению в @GrpcClient
      address: 'discovery:///collector' # адрес gRPC-сервиса
      enableKeepAlive: true
      keepAliveWithoutCalls: true
      negotiation-type: plaintext