spring:
  application:
    name: main-service
  config:
#    import: configserver:http://localhost:8888
    import: "configserver:"
  cloud:
    config:
      fail-fast: true
      retry:
        useRandomPolicy: true
        max-interval: 6000
      discovery:
        enabled: true
        serviceId: config-server

eureka:
  client:
    enable: true
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
#      defaultZone: http://localhost:8761/eureka/
      defaultZone: http://${eureka.instance.hostname:localhost}:${eureka.instance.port:8761}/eureka/
  instance:
    preferIpAddress: true
    hostname: localhost
    instance-id: "${spring.application.name}:${random.value}"
#    instance-id: "${spring.application.name}:${spring.application.instance_id:${random.value}}"
# Первая строка назначает для server.port значение переменной PORT (если она существует),
# если нет, то 0. Это заставляет Spring Boot назначить случайный, неиспользуемый порт.
# Вторая строка добавляет текущий spring.application.instance_id (если он существует)
# к spring.application.name, разделённому двоеточием (: ). Если spring.application.instance_id не существует,
# то добавляется случайное значение для создания уникального идентификатора экземпляра Eureka
# для этого экземпляра.
    leaseRenewalIntervalInSeconds: 10